In [2]:
import numpy as np

In [11]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
b = np.random.randint(0, 10, (5,5))
print(b)

[[2 9 1 0 8]
 [4 7 4 1 8]
 [4 9 5 4 4]
 [5 6 6 1 4]
 [6 8 3 3 8]]


In [21]:
b = np.random.random((4,4))
print(b)

[[0.20203671 0.86156426 0.37587689 0.16367835]
 [0.46881389 0.1117205  0.63020764 0.261263  ]
 [0.92002252 0.62063341 0.24974216 0.13095503]
 [0.40148066 0.64024108 0.06791147 0.59949235]]


In [28]:
a = np.random.randint(0, 10, (5))
b = np.random.randint(0, 10, (5))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[8 0 7 4 9]
[9 5 3 0 8]
[17  5 10  4 17]
[-1 -5  4  4  1]
[72  0 21  0 72]


In [29]:
a = np.random.randint(0, 10, (5))
b = np.random.randint(0, 10, (5))
print(a)
print(b)
print(np.dot(a, b))

[1 5 2 2 1]
[2 1 0 0 9]
16


In [37]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,3))
print(a)
print(b)
print(np.dot(a, b))

[[8 6]
 [3 4]]
[[5 1 7]
 [1 7 3]]
[[46 50 74]
 [19 31 33]]


In [4]:
a = np.random.randint(1, 10, (3,3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[1 6 5]
 [4 9 4]
 [8 3 4]]
[[-0.13333333  0.05        0.11666667]
 [-0.08888889  0.2        -0.08888889]
 [ 0.33333333 -0.25        0.08333333]]


In [42]:
a = np.random.random((4,4))
b = a.T
print(a)
print(b)

[[0.31722266 0.37151881 0.94608787 0.92649928]
 [0.45370411 0.91081812 0.48154176 0.97745834]
 [0.29725768 0.41694006 0.92627127 0.74491259]
 [0.31605041 0.08879427 0.62574264 0.63436383]]
[[0.31722266 0.45370411 0.29725768 0.31605041]
 [0.37151881 0.91081812 0.41694006 0.08879427]
 [0.94608787 0.48154176 0.92627127 0.62574264]
 [0.92649928 0.97745834 0.74491259 0.63436383]]


In [9]:
a = np.random.randint(1, 10, (3,4))
b = np.random.randint(1, 10, (4))
print(a)
print(b)
print(np.dot(a, b))

[[4 3 2 2]
 [3 8 1 7]
 [6 5 9 3]]
[9 7 1 2]
[ 63  98 104]


In [10]:
a = np.random.random((2,3))
b = np.random.random((3))
print(a)
print(b)
print(np.dot(a, b))

[[0.88284171 0.58815617 0.19682629]
 [0.51019372 0.04786637 0.1807902 ]]
[0.03537849 0.23900671 0.84658045]
[0.33843616 0.18254371]


In [11]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,2))
print(a)
print(b)
print(a*b)

[[2 7]
 [4 7]]
[[2 5]
 [9 4]]
[[ 4 35]
 [36 28]]


In [12]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,2))
print(a)
print(b)
print(a+b)

[[5 1]
 [3 1]]
[[5 3]
 [6 5]]
[[10  4]
 [ 9  6]]


In [14]:
a = np.random.randint(1, 100, (5,5))
print(a)
print(a.sum())

[[63 61  2 87 30]
 [88  2 10 95 18]
 [40 45 96 96 22]
 [27 14 47 97 89]
 [69 50 37 35 20]]
1240


In [17]:
a = np.random.randint(1, 10, (4,4))
b = np.random.randint(1, 10, (4,4))
sum_a = a.sum()
sum_b = b.sum()
print(sum_a-sum_b)

24


In [22]:
a = np.random.random((3,3))
print(a)
vector = a.sum(axis=1).reshape(3,1)
print(vector)

[[0.79939835 0.64270816 0.04618123]
 [0.17539129 0.80829324 0.17389852]
 [0.35904676 0.56191145 0.39014713]]
[[1.48828775]
 [1.15758305]
 [1.31110534]]


In [40]:
a = np.random.randint(1,10, size=(3,4))
square = a*a
square2 = np.square(a)
print(a)
print(square)
print(square2)

[[7 2 3 9]
 [5 2 8 6]
 [4 8 2 4]]
[[49  4  9 81]
 [25  4 64 36]
 [16 64  4 16]]
[[49  4  9 81]
 [25  4 64 36]
 [16 64  4 16]]


In [39]:
a = np.random.randint(1, 50, (4))
b = np.sqrt(a)
print(a)
print(b)

[46 38 36  3]
[6.78232998 6.164414   6.         1.73205081]
