In [4]:
import numpy as np

In [11]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
b = np.random.randint(0, 10, (5,5))
print(b)

[[2 9 1 0 8]
 [4 7 4 1 8]
 [4 9 5 4 4]
 [5 6 6 1 4]
 [6 8 3 3 8]]


In [21]:
b = np.random.random((4,4))
print(b)

[[0.20203671 0.86156426 0.37587689 0.16367835]
 [0.46881389 0.1117205  0.63020764 0.261263  ]
 [0.92002252 0.62063341 0.24974216 0.13095503]
 [0.40148066 0.64024108 0.06791147 0.59949235]]


In [28]:
a = np.random.randint(0, 10, (5))
b = np.random.randint(0, 10, (5))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[8 0 7 4 9]
[9 5 3 0 8]
[17  5 10  4 17]
[-1 -5  4  4  1]
[72  0 21  0 72]


In [29]:
a = np.random.randint(0, 10, (5))
b = np.random.randint(0, 10, (5))
print(a)
print(b)
print(np.dot(a, b))

[1 5 2 2 1]
[2 1 0 0 9]
16


In [37]:
a = np.random.randint(1, 10, (2,2))
b = np.random.randint(1, 10, (2,3))
print(a)
print(b)
print(np.dot(a, b))

[[8 6]
 [3 4]]
[[5 1 7]
 [1 7 3]]
[[46 50 74]
 [19 31 33]]


In [38]:
a = np.random.randint(1, 10, (3,3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[7 8]
 [1 9]]
[[ 0.16363636 -0.14545455]
 [-0.01818182  0.12727273]]


In [42]:
a = np.random.random((4,4))
b = a.T
print(a)
print(b)

[[0.31722266 0.37151881 0.94608787 0.92649928]
 [0.45370411 0.91081812 0.48154176 0.97745834]
 [0.29725768 0.41694006 0.92627127 0.74491259]
 [0.31605041 0.08879427 0.62574264 0.63436383]]
[[0.31722266 0.45370411 0.29725768 0.31605041]
 [0.37151881 0.91081812 0.41694006 0.08879427]
 [0.94608787 0.48154176 0.92627127 0.62574264]
 [0.92649928 0.97745834 0.74491259 0.63436383]]
